POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Unite Summit 2",
    "details": "Um evento para quem é apaixonado por programação nodejs",
    "maximumAttendees": 100
}